#!/bin/bash

required_packages=(openssl tcpserver)
PASSWORD="bacon"
ENCRYPTION=1
PORT=8888
socat_server="socat tcp4-listen:${PORT},reuseaddr,ignoreeof,fork stdin"


crypt(){
#Takes a message from $1 and returns the encrypted and base64 encoded message
MSG="${1}"

	if [ -z "${MSG}" ]; then 
	  echo "crypt needs a string"
	  exit -1
	fi

	CRYPT_MSG=$(echo ${MSG} | openssl enc -aes-256-cbc -pbkdf2 -a -pass pass:$(echo ${PASSWORD}))
}

dcrypt(){
#Takes an encrypted and base64 encoded message and returns the cleartext version
MSG=${1}
	if [ -z "${MSG}" ]; then 
	  echo "crypt needs a string"
	  exit -1
	fi

	CLEARTEXT_MSG=$(echo ${MSG} | openssl enc -d -aes-256-cbc -pbkdf2 -a -pass pass:$(echo ${PASSWORD}))
}

$(${socat_server}) &
while :
 	do
	unset data
 	while [ -z ${data} ]; do
	  read -rp "message: " data
	done

if [ $data = "_" ]; then #om man skriver _ ska man sen skriva hur många rader meddelanden man vill visa
        echo -n "lines:"
        read  number
	if [ ${number} -le 0 ]
	 then
	   #Do Nothing		
		:
	elif [ ${number} -gt 0 ]
	 then 	
        tail -$number fil.txt
	fi
else #inget speciellt tecken, ett meddelande
	if [ ${ENCRYPTION} -eq 1 ]
	 then	
		#Encryption is turned on
		crypt ${data}
		echo "${CRYPT_MSG}" >> fil.txt
	 else
		echo "${data}" >> fil.txt
	fi
fi

done
